const userTypes = {
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  SIGN_IN_SUCCES: " SIGN_IN_SUCCES",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGN_OUT_USER_START: "SIGN_OUT_USER_START",
  SIGN_OUT_USER_SUCCES: "SIGN_OUT_USER_SUCCES",
  SIGN_UP_USER_START: "SIGN_UP_USER_START",
  RESET_PASSWORD_START: "RESET_PASSWORD_START",
  RESET_PASSWORD_SUCCES: "RESET_PASSWORD_SUCCES",
  USER_ERROR: "USER_ERROR",
  RESET_USER_STATE: "RESET_USER_STATE",
  GOOGLE_SIGNIN_START: "GOOGLE_SIGNIN_START",

  /*SET_CURRENT_USER: "SET_CURRENT_USER",
  RESET_AUTH_FORMS: "RESET_AUTH_FORMS",*/
};

export default userTypes;
